# Generated by Django 3.2.8 on 2021-11-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='dd', upload_to='pictures'),
            preserve_default=False,
        ),
    ]
